### ISSUE TITLE
Serialized data must be a string containing serialized PHP code; received: NULL

### ISSUE THREAD

**Issue by CreativeNative** [zendframework/zend-serializer#18]
After updating to version 2.7.2 I got following error on my login page.

`PHP Fatal error:  Uncaught exception 'Zend\\Serializer\\Exception\\RuntimeException' with message 'Serialized data must be a string containing serialized PHP code; received: NULL' in vendor/zendframework/zend-serializer/src/Adapter/PhpSerialize.php:75\nStack trace:\n#0 vendor/zendframework/zend-cache/src/Storage/Plugin/Serializer.php(72): Zend\\Serializer\\Adapter\\PhpSerialize->unserialize(NULL)\n#1 [internal function]: Zend\\Cache\\Storage\\Plugin\\Serializer->onReadItemPost(Object(Zend\\Cache\\Storage\\PostEvent))\n#2 vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\\Cache\\Storage\\PostEvent))\n#3 vendor/zendframework/zend-eventmanager/src/EventManager.php(251): Zend\\EventManager\\EventManager->triggerListeners('getItem.post', Object(Zend\\Cache\\Storage\\PostEvent))\n#4 vendor/zendframework/ in vendor/zendframework/zend-serializer/src/Adapter/PhpSerialize.php on line 75`

**Comment by rizzdev** [comment]
I am also having this issue, hope to see a solution soon. This started happening.

**Comment by weierophinney** [comment]
Could one of you explain the use case for serializing null values, please? I'm trying to understand the problem better...

**Comment by dymen1** [comment]
@weierophinney in my case it is happening because the result of a Zend\Cache\Storage\PostEvent is null the event triggered is getItem.post by \Zend\Cache\Storage\Adapter\AbstractAdapter::triggerPost

**Comment by andreasKrauseWebular** [comment]
+1
same here after update to 2.7.2 this morning
framework just starts with this Fatal Error

**Comment by ghost** [comment]
+1
Same here. Zend throws Exception after Update but I did not change anything

**Comment by trybguet-dev** [comment]
same here

**Comment by someother1** [comment]
+1
Same here.. i can see that the error occurs in the Module.php / onBootstrap - on the way to fetch the acl via bjyauthorize:

`$oBjyAuthorize = $oServiceManager->get('BjyAuthorizeServiceAuthorize');
        $oACL = $oBjyAuthorize->getAcl();
        $oIdentity = $oBjyAuthorize->getIdentity();`

**Comment by Koopzington** [comment]
+1
In my case it's BjAuthorize causing this issue while calling $cache->getItem() here:
[BjyAuthorize\Service\Authorize](https://github.com/bjyoungblood/BjyAuthorize/blob/1.4.0/src/BjyAuthorize/Service/Authorize.php#L266)

$result is empty at the marked line in [Zend\Storage\Adapter\AbstractAdapter](https://github.com/zendframework/zend-cache/blob/release-2.7.0/src/Storage/Adapter/AbstractAdapter.php#L221)

and with [Zend\Cache\Storage\Plugin\Serializer](https://github.com/zendframework/zend-cache/blob/release-2.7.0/src/Storage/Plugin/Serializer.php#L72) trying to unserialize null everything blows up.

I've already seen that @marc-mabe [posted a fix for that](https://github.com/zendframework/zend-cache/commit/06308883cc3d63d11a24188a8ba312f143b9afd7) to avoid this but that change isn't in the latest tag, so i guess releasing [2.7.1](https://github.com/zendframework/zend-cache/milestones/2.7.1) for Zend\Cache would fix this, right?

**Comment by weierophinney** [comment]
The problem is due to merging #9, which was created by @marc-mabe in large part to support the changes he has done in zend-cache as linked by @Koopzington ; essentially, the JSON serializer was not behaving in the same way as the other serializers. The reason there's no 2.7.1 tag on zend-cache is because it was blocked on this fix.

I've now got a conundrum: I don't feel comfortable releasing the zend-cache fix as I don't know if there are other fixes pending for that release, but I also don't want all of you to have broken code.

The short-term fix is to pin to zend-serializer 2.7.1:

``` bash
composer require "zendframework/zend-serializer:2.7.1"
```

and then check to see when zend-cache 2.7.1 releases (at which point you'd pin to `zendframework/zend-serializer:^2.7.2`). 

Let's see what @marc-mabe has to say... If I don't hear back by tomorrow, I'll revert the change.

**Comment by joe-liquid** [comment]
+1
Me too. Serialized data must be a string containing serialized PHP code; received: NULL

**Comment by marc-mabe** [comment]
@weierophinney I just checked what's in zend-cache 2.7.1 and it all can be released!
Sorry for the delay of my work but for the last weeks my head is spinning on totally different things (pyspark) why I was not able find enough time switching back to zend /:

@weierophinney could you tag the new release of zend-cache please. Thanks!

**Comment by weierophinney** [comment]
@marc-mabe Thanks for the info!

To those who have reported the issue: please do a `composer update`, and verify you have received zend-cache 2.7.1, and then test again. Report back with your results (i.e., did it fix the issue for you or no?)

Thanks!

**Comment by someother1** [comment]
updated and got:
zendframework/zend-serializer (2.7.2)
zendframework/zend-cache (2.7.1)

which works perfect - thank you

**Comment by ghost** [comment]
- Removing zendframework/zend-cache (2.7.0)
- Installing zendframework/zend-cache (2.7.1)
  Downloading: 100%         
- Removing zendframework/zend-serializer (2.7.1)
- Installing zendframework/zend-serializer (2.7.2)
  Loading from cache

=> Site is working again

**Comment by Koopzington** [comment]
Aye! stuff is working again! Thanks!

**Comment by dymen1** [comment]
The update fixed it!
