### ISSUE TITLE
Failed test with PHP 7.x

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-serializer#23]
Discovered in Fedora CI, https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-serializer?collection=f25

```
There was 1 failure:
1) ZendTest\Serializer\Adapter\WddxTest::testUnserializeFalse
Failed asserting that true matches expected false.
/builddir/build/BUILD/zend-serializer-ff74ea020f5f90866eb28365327e9bc765a61a6e/test/Adapter/WddxTest.php:136
FAILURES!
```

Not detected by travis as wddx extension is not available, and not yet covered by PHP test suite.
Can you please enable it ?

This is an upstream bug, see https://bugs.php.net/bug.php?id=72564
Fix will be in 7.0.10

So mostly for your information

**Comment by marc-mabe** [comment]
@remicollet Thanks for your bug report and info! I tried to enable/install the wddx extension on travis but failed because it's not available in travis and there is no pecl extension available. Do you have an idea how I can install this extension?

**Comment by remicollet** [comment]
Sorry, but I have no idea how to do this on travis

**Comment by marc-mabe** [comment]
@remicollet Is that still an issue or can we close it?

**Comment by remicollet** [comment]
The issue exists in old PHP version, so this can probably be closed.

**Comment by marc-mabe** [comment]
Closed as not an issue anymore
