### ISSUE TITLE
Class 'Zend\Serializer\Serializer' not found

### ISSUE THREAD

**Issue by newbie78** [zendframework/zend-serializer#28]
Apache/2.4.20 (Win32) PHP/5.6.21
Exception in …\vendor\zendframework\zend-cache\src\Storage\Plugin\PluginOptions.php:215 
```
$cache = StorageFactory::factory([
			'adapter' => [
				'name' => 'filesystem',
				'options'=>[
					'cache_dir'=>'.\filessys\local\tabletka\',
				]
			],
			'plugins' => [
				// Don't throw exceptions on cache errors
				'exception_handler' => [
					'throw_exceptions' => false
				],
				'serializer',
			],
		]);
```

**Comment by Xerkus** [comment]
You didn't install suggested dependency required to use serializer plugin.
Do `composer require zendframework/zend-serializer `

**Comment by newbie78** [comment]
thx for answer!

im install zendframework/zend-cache but zendframework/zend-serializer in require-dev section in it's composer.json file
okay

**Comment by marc-mabe** [comment]
@newbie78 if you need the serializing feature in development mode only it's ok else but it the same section as zend-cache. Please read composer documentation!
